# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghorg < Formula
  desc "Quickly clone an entire org/users repositories into one directory"
  homepage "https://github.com/gabrie30/ghorg"
  version "1.7.16"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gabrie30/ghorg/releases/download/v1.7.16/ghorg_1.7.16_Darwin_x86_64.tar.gz"
      sha256 "045cd01a33446b557f8e06f7971ee67baf9153cf8af2a979949649623dfbc4f2"

      def install
        bin.install "ghorg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gabrie30/ghorg/releases/download/v1.7.16/ghorg_1.7.16_Darwin_arm64.tar.gz"
      sha256 "7f33057b31c793cd46ca82e254751d2ce6e79cf5462ac100455bfec995d30aae"

      def install
        bin.install "ghorg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gabrie30/ghorg/releases/download/v1.7.16/ghorg_1.7.16_Linux_arm64.tar.gz"
      sha256 "8679e149509463f8274e31f98856fa71c18e45c262afcf76de151b7a5594e91e"

      def install
        bin.install "ghorg"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gabrie30/ghorg/releases/download/v1.7.16/ghorg_1.7.16_Linux_x86_64.tar.gz"
      sha256 "f15fa15acb353339bffed7b9842107ac2088e0b8abadfb9e94eb23ae77922905"

      def install
        bin.install "ghorg"
      end
    end
  end

  def post_install
    ohai ""
    ohai "***************************"
    ohai "For examples on how to use ghorg see: https://github.com/gabrie30/ghorg/tree/master/examples"
    ohai ""
    ohai "Remember to set your $HOME/.config/ghorg/conf.yaml"
    ohai ""
    ohai "Here's all you need to do..."
    ohai "1) mkdir -p $HOME/.config/ghorg"
    ohai "2) curl https://raw.githubusercontent.com/gabrie30/ghorg/master/sample-conf.yaml > $HOME/.config/ghorg/conf.yaml"
    ohai "***************************"
    ohai ""
  end

  test do
    system "#{bin}/ghorg version"
  end
end
