# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghorg < Formula
  desc "Quickly clone an entire org/users repositories into one directory"
  homepage "https://github.com/gabrie30/ghorg"
  version "1.9.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gabrie30/ghorg/releases/download/v1.9.2/ghorg_1.9.2_Darwin_arm64.tar.gz"
      sha256 "90cbca7c72e8934f922346ba067d47a57b7bdf4321843441f88ae03c26016a80"

      def install
        bin.install "ghorg"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gabrie30/ghorg/releases/download/v1.9.2/ghorg_1.9.2_Darwin_x86_64.tar.gz"
      sha256 "247cf1ac0a1507abb4cf0a2adb955f1a70ee2d399963b177b7f39a18e7c37720"

      def install
        bin.install "ghorg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gabrie30/ghorg/releases/download/v1.9.2/ghorg_1.9.2_Linux_arm64.tar.gz"
      sha256 "e00e1cd1e02524ee074250de261343e3ca2d248e3ef807dede91e9bc499133ad"

      def install
        bin.install "ghorg"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gabrie30/ghorg/releases/download/v1.9.2/ghorg_1.9.2_Linux_x86_64.tar.gz"
      sha256 "70a07cdceb0926342c9857ab00cb851383ee718f4cc8107e0f330c7f256591f8"

      def install
        bin.install "ghorg"
      end
    end
  end

  def post_install
    ohai ""
    ohai "***************************"
    ohai "For examples on how to use ghorg see: https://github.com/gabrie30/ghorg/tree/master/examples"
    ohai ""
    ohai "Remember to set your $HOME/.config/ghorg/conf.yaml"
    ohai ""
    ohai "Here's all you need to do..."
    ohai "1) mkdir -p $HOME/.config/ghorg"
    ohai "2) curl https://raw.githubusercontent.com/gabrie30/ghorg/master/sample-conf.yaml > $HOME/.config/ghorg/conf.yaml"
    ohai "***************************"
    ohai ""
  end

  test do
    system "#{bin}/ghorg version"
  end
end
