# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghorg < Formula
  desc "Quickly clone an entire org/users repositories into one directory"
  homepage "https://github.com/gabrie30/ghorg"
  version "1.8.7"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gabrie30/ghorg/releases/download/v1.8.7/ghorg_1.8.7_Darwin_x86_64.tar.gz"
      sha256 "de1653987bc542b70bf048a2f7aa26a93a08423a5e742e19116c3932f1197e32"

      def install
        bin.install "ghorg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gabrie30/ghorg/releases/download/v1.8.7/ghorg_1.8.7_Darwin_arm64.tar.gz"
      sha256 "11ee36dea0a0f90ba6167a3810241d66f13408eed1793794a695c69549e9d2c6"

      def install
        bin.install "ghorg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gabrie30/ghorg/releases/download/v1.8.7/ghorg_1.8.7_Linux_x86_64.tar.gz"
      sha256 "9534dff15434c0b52bdeb6aa9695aa8d241b659f80ab5c3cb811339e12d5acb1"

      def install
        bin.install "ghorg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gabrie30/ghorg/releases/download/v1.8.7/ghorg_1.8.7_Linux_arm64.tar.gz"
      sha256 "10f988f2373a76d380a78f1703be828510ab4f10e22ca49159afe0bd79b7457d"

      def install
        bin.install "ghorg"
      end
    end
  end

  def post_install
    ohai ""
    ohai "***************************"
    ohai "For examples on how to use ghorg see: https://github.com/gabrie30/ghorg/tree/master/examples"
    ohai ""
    ohai "Remember to set your $HOME/.config/ghorg/conf.yaml"
    ohai ""
    ohai "Here's all you need to do..."
    ohai "1) mkdir -p $HOME/.config/ghorg"
    ohai "2) curl https://raw.githubusercontent.com/gabrie30/ghorg/master/sample-conf.yaml > $HOME/.config/ghorg/conf.yaml"
    ohai "***************************"
    ohai ""
  end

  test do
    system "#{bin}/ghorg version"
  end
end
